#!/usr/bin/env python3
"""
CHIP-8 Key Configuration Generator
===================================
Place this script in any directory with CHIP-8 ROM files (.ch8, .CH8).
It will help you create/edit key config files for each ROM.

Physical keys on M5Cardputer:
  ; = up
  . = down
  , = left
  / = right
  Enter/Space = action

These map to CHIP-8 hex keys (0-F) based on each game's needs.
"""

import os
import sys

# Common game control presets
PRESETS = {
    "1": {
        "name": "D-Pad Standard (2=up, 8=down, 4=left, 6=right, 5=action)",
        "config": {"up": "2", "down": "8", "left": "4", "right": "6", "action": "5"}
    },
    "2": {
        "name": "Tetris (4=left, 5=rotate, 6=right, 2=drop)",
        "config": {"up": "5", "down": "2", "left": "4", "right": "6", "action": "0"}
    },
    "3": {
        "name": "Space Invaders (4=left, 5=shoot, 6=right)",
        "config": {"up": "5", "down": "5", "left": "4", "right": "6", "action": "5"}
    },
    "4": {
        "name": "Pong (1=up, 4=down)",
        "config": {"up": "1", "down": "4", "left": "0", "right": "0", "action": "0"}
    },
    "5": {
        "name": "Custom (you specify each key)",
        "config": None
    }
}


def find_roms(directory="."):
    """Find all CHIP-8 ROM files in directory"""
    roms = []
    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        # Include .ch8 files OR extensionless files that aren't hidden/config
        if filename.lower().endswith('.ch8'):
            roms.append(filename)
        elif (os.path.isfile(filepath) and
              '.' not in filename and
              not filename.startswith('.') and
              not filename.endswith('.cfg')):
            roms.append(filename)
    return sorted(roms)


def config_exists(rom_path):
    """Check if config file exists for ROM"""
    return os.path.exists(rom_path + ".cfg")


def read_config(config_path):
    """Read existing config file"""
    config = {}
    if not os.path.exists(config_path):
        return None

    with open(config_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                config[key.strip()] = value.strip()
    return config


def write_config(config_path, config, rom_name=""):
    """Write config file"""
    with open(config_path, 'w') as f:
        f.write(f"# CHIP-8 Key Configuration for {rom_name}\n")
        f.write("# Generated by chip8_config_generator.py\n")
        f.write("#\n")
        f.write("# Physical keys -> CHIP-8 hex keys:\n")
        f.write("#   ; (up)    -> key specified by 'up='\n")
        f.write("#   . (down)  -> key specified by 'down='\n")
        f.write("#   , (left)  -> key specified by 'left='\n")
        f.write("#   / (right) -> key specified by 'right='\n")
        f.write("#   Enter     -> key specified by 'action='\n")
        f.write("#\n")
        f.write("# Values are CHIP-8 hex keys (0-F)\n")
        f.write("\n")
        f.write(f"up={config['up']}\n")
        f.write(f"down={config['down']}\n")
        f.write(f"left={config['left']}\n")
        f.write(f"right={config['right']}\n")
        f.write(f"action={config['action']}\n")


def get_custom_config():
    """Get custom key mappings from user"""
    config = {}

    print("\nEnter CHIP-8 hex key for each direction (0-F):")
    print("Example: Tetris uses 4=left, 5=rotate, 6=right, 2=drop")
    print()

    while True:
        val = input("Up (; key) maps to CHIP-8 key (0-F): ").strip().upper()
        if val in "0123456789ABCDEF" and len(val) == 1:
            config['up'] = val
            break
        print("  Invalid! Enter a single hex digit (0-F)")

    while True:
        val = input("Down (. key) maps to CHIP-8 key (0-F): ").strip().upper()
        if val in "0123456789ABCDEF" and len(val) == 1:
            config['down'] = val
            break
        print("  Invalid! Enter a single hex digit (0-F)")

    while True:
        val = input("Left (, key) maps to CHIP-8 key (0-F): ").strip().upper()
        if val in "0123456789ABCDEF" and len(val) == 1:
            config['left'] = val
            break
        print("  Invalid! Enter a single hex digit (0-F)")

    while True:
        val = input("Right (/ key) maps to CHIP-8 key (0-F): ").strip().upper()
        if val in "0123456789ABCDEF" and len(val) == 1:
            config['right'] = val
            break
        print("  Invalid! Enter a single hex digit (0-F)")

    while True:
        val = input("Action (Enter key) maps to CHIP-8 key (0-F): ").strip().upper()
        if val in "0123456789ABCDEF" and len(val) == 1:
            config['action'] = val
            break
        print("  Invalid! Enter a single hex digit (0-F)")

    return config


def configure_rom(rom_path):
    """Interactive config for a single ROM"""
    rom_name = os.path.basename(rom_path)
    config_path = rom_path + ".cfg"

    print(f"\n{'='*60}")
    print(f"Configuring: {rom_name}")
    print('='*60)

    # Check if config exists
    existing = read_config(config_path)
    if existing:
        print(f"\n✓ Config file already exists: {config_path}")
        print("\nCurrent mappings:")
        for key, val in existing.items():
            print(f"  {key:8} = {val}")

        choice = input("\nOverwrite? (y/N): ").strip().lower()
        if choice != 'y':
            print("Skipped.")
            return False

    # Show presets
    print("\nSelect control preset:")
    for key, preset in PRESETS.items():
        print(f"  {key}. {preset['name']}")

    choice = input("\nChoice (1-5): ").strip()

    if choice in PRESETS:
        preset = PRESETS[choice]
        if preset['config']:
            config = preset['config']
            print(f"\n✓ Using preset: {preset['name']}")
        else:
            config = get_custom_config()
    else:
        print("Invalid choice, using custom...")
        config = get_custom_config()

    # Write config
    write_config(config_path, config, rom_name)
    print(f"\n✓ Config saved: {config_path}")

    return True


def main():
    print("="*60)
    print("CHIP-8 Key Configuration Generator")
    print("="*60)

    # Check for batch mode
    batch_mode = "--batch" in sys.argv
    if batch_mode:
        sys.argv.remove("--batch")

    # Get directory
    if len(sys.argv) > 1:
        directory = sys.argv[1]
    else:
        directory = "."

    if not os.path.isdir(directory):
        print(f"Error: '{directory}' is not a directory")
        sys.exit(1)

    # Batch mode - apply D-Pad Standard to all ROMs
    if batch_mode:
        roms = find_roms(directory)
        if not roms:
            print("\n⚠ No CHIP-8 ROM files found")
            sys.exit(0)

        print(f"\nBatch mode: Applying D-Pad Standard config to {len(roms)} ROM(s)")
        config = PRESETS["1"]["config"]

        for rom in roms:
            rom_path = os.path.join(directory, rom)
            config_path = rom_path + ".cfg"
            write_config(config_path, config, rom)
            print(f"  ✓ {rom}")

        print(f"\n✓ Created {len(roms)} config file(s)")
        sys.exit(0)

    print(f"\nScanning directory: {os.path.abspath(directory)}")

    # Find ROMs
    roms = find_roms(directory)

    if not roms:
        print("\n⚠ No CHIP-8 ROM files found (.ch8, .CH8)")
        print("Place this script in a directory with ROM files.")
        sys.exit(0)

    print(f"\nFound {len(roms)} ROM(s):")
    for rom in roms:
        status = "✓ has config" if config_exists(os.path.join(directory, rom)) else "✗ no config"
        print(f"  {rom:30} [{status}]")

    # Interactive mode
    print("\n" + "="*60)
    print("Configure ROMs:")
    print("  1. Configure all ROMs (create missing configs)")
    print("  2. Configure specific ROM")
    print("  3. Reconfigure all ROMs (overwrite existing)")
    print("  4. Exit")

    choice = input("\nChoice (1-4): ").strip()

    if choice == "1":
        # Configure ROMs without configs
        unconfigured = [r for r in roms if not config_exists(os.path.join(directory, r))]
        if not unconfigured:
            print("\n✓ All ROMs already have configs!")
        else:
            for rom in unconfigured:
                configure_rom(os.path.join(directory, rom))

    elif choice == "2":
        # Configure specific ROM
        print("\nSelect ROM:")
        for i, rom in enumerate(roms, 1):
            print(f"  {i}. {rom}")

        try:
            idx = int(input("\nROM number: ").strip()) - 1
            if 0 <= idx < len(roms):
                configure_rom(os.path.join(directory, roms[idx]))
            else:
                print("Invalid ROM number")
        except ValueError:
            print("Invalid input")

    elif choice == "3":
        # Reconfigure all
        confirm = input(f"\nReconfigure all {len(roms)} ROMs? (y/N): ").strip().lower()
        if confirm == 'y':
            for rom in roms:
                configure_rom(os.path.join(directory, rom))

    else:
        print("\nExiting...")

    print("\n" + "="*60)
    print("Done! Transfer the .cfg files to your SD card alongside the ROMs.")
    print("="*60)


if __name__ == "__main__":
    main()
